import type { Metadata } from "next";
import { craftingStyles } from "galadrielcss";
import "./globals.css";
// Importing the CSS file generated by Galadriel.CSS
import "./layout.css";

export const metadata: Metadata = {
    title: "Galadriel.CSS | Showcasing Navbar",
    description: "Showcasing Navbar",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const html = craftingStyles(() => ({
		height: "100vh",
		width: "100vw",
		padding: "0",
		margin: "0",
	}));

    const body = craftingStyles(() => ({
        display: "flex",
        justifyContent: "center",
        alignItems: "start",
		height: "100%",
		width: "100%",
		padding: "0",
		margin: "0",
	}));

    return (
        <html lang="en" className={html}>
            <body className={body}>{children}</body>
        </html>
    );
}
